name = "RLinearAlgebra"
uuid = "da1d211a-c3bc-43b2-b5d0-ce83f16a0f3a"
authors = ["Vivak Patel <vivak.patel@wisc.edu>", "Daniel Adrian Maldonado <maldonadod@anl.gov>"]
version = "0.1.8"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
